POST http://localhost:8080/api/categories
content-type: application/json

{
  "name": "Drama",
  "description": "Description of the Action"
}

###
GET http://localhost:8080/api/categories

###

GET http://localhost:8080/api/categories/10

###
PUT http://localhost:8080/api/categories/6
content-type: application/json

{
    "name": "Drama 2",
    "description": "Updated description of the category 1"
}

###
DELETE http://localhost:8080/api/categories/20

###
GET http://localhost:8080/api/categories/3/films